// // model/cubes/nation_region_dynamic.js
// //
// // Two static cubes (nation, region) with a dynamically built join — defined
// // inside asyncModule(), Cube's documented mechanism for dynamic data models
// // and the SAME code path as dynamic_cubes.js (which compiles successfully in
// // this deployment: the dce_* cubes exist).
// //
// // Inside asyncModule the transpiler is out of the picture entirely, so ALL
// // sql values must be functions — dimensions, sql_table, and join sql alike.
// //
// // IMPORTANT: delete any other files defining `nation` or `region` first
// // (nation.yml, region.yml, nation.js, nation_region.js, nation_region.yml),
// // or the model fails with a duplicate-cube error.

// // ---------------------------------------------------------------------------
// // Join config: one entry per join edge. Add entries to add joins.
// // ---------------------------------------------------------------------------
// const DYNAMIC_JOIN_CONFIG = [
//   {
//     from: 'nation',
//     to: 'region',
//     localColumn: 'N_REGIONKEY',
//     foreignColumn: 'R_REGIONKEY',
//     relationship: 'many_to_one',
//   },
//   {
//     from: 'nation',
//     to: 'dce_region', // generated by dynamic_cubes.js — name must match CUBE_PREFIX + table
//     localColumn: 'N_REGIONKEY',
//     foreignColumn: 'R_REGIONKEY',
//     relationship: 'many_to_one',
//   },
// ];

// // Builds the joins object for one cube.
// //  - zero-parameter sql functions returning raw SQL
// //  - both aliases QUOTED: Cube emits quoted lowercase aliases (AS "region"),
// //    and Snowflake uppercases unquoted identifiers, so an unquoted reference
// //    fails with "invalid identifier"
// function buildDynamicJoins(cubeName, joinConfig) {
//   const joins = {};
//   for (const j of joinConfig) {
//     if (j.from !== cubeName) continue;
//     const target = j.to; // per-iteration const => safe closure capture
//     joins[target] = {
//       relationship: j.relationship,
//       sql: () => `"${j.from}"."${j.localColumn}" = "${target}"."${j.foreignColumn}"`,
//     };
//   }
//   return joins;
// }

// asyncModule(async () => {
//   // -------------------------------------------------------------------------
//   // region
//   // -------------------------------------------------------------------------
//   cube('region', {
//     sql_table: () => 'TPCH_SF100.REGION',
//     // TRUE while verifying (hidden cubes don't show in /v1/meta or the
//     // Playground); flip to false afterwards if desired — the join keeps
//     // working either way.
//     public: true,

//     // No config entries originate FROM region today => {}.
//     joins: buildDynamicJoins('region', DYNAMIC_JOIN_CONFIG),

//     dimensions: {
//       region_key: {
//         sql: (CUBE) => `${CUBE}."R_REGIONKEY"`,
//         type: 'number',
//         primary_key: true,
//       },
//       name: {
//         sql: (CUBE) => `${CUBE}."R_NAME"`,
//         type: 'string',
//         description: 'Region name (e.g. AMERICA, EUROPE, ASIA)',
//       },
//       comment: {
//         sql: (CUBE) => `${CUBE}."R_COMMENT"`,
//         type: 'string',
//       },
//     },

//     measures: {
//       count: {
//         type: 'count',
//         description: 'Total number of regions',
//       },
//     },
//   });

//   // -------------------------------------------------------------------------
//   // nation
//   // -------------------------------------------------------------------------
//   cube('nation', {
//     sql_table: () => 'TPCH_SF100.NATION',
//     public: true,

//     joins: buildDynamicJoins('nation', DYNAMIC_JOIN_CONFIG),

//     dimensions: {
//       nation_key: {
//         sql: (CUBE) => `${CUBE}."N_NATIONKEY"`,
//         type: 'number',
//         primary_key: true,
//       },
//       name: {
//         sql: (CUBE) => `${CUBE}."N_NAME"`,
//         type: 'string',
//         description: 'Nation name',
//       },
//       region_key: {
//         sql: (CUBE) => `${CUBE}."N_REGIONKEY"`,
//         type: 'number',
//       },
//       comment: {
//         sql: (CUBE) => `${CUBE}."N_COMMENT"`,
//         type: 'string',
//       },
//     },

//     measures: {
//       count: {
//         type: 'count',
//         description: 'Total number of nations',
//       },
//     },
//   });
// });