views:
  - name: otm_author_view

    cubes:
      - join_path: otm_author
        includes: "*"

      - join_path: otm_author.otm_book
        prefix: true
        includes:
          - id
          - book
          - award
          - count
